### ISSUE TITLE
java.lang.NullPointerException at com.github.dariobalinzo.task.ElasticSourceTask.fetchLastOffset(ElasticSourceTask.java:215)

### ISSUE THREAD

**Issue by david-espinosa** [DarioBalinzo/kafka-connect-elasticsearch-source#1]
Hi!
I'm having this error when using your connector:

java.lang.NullPointerException at com.github.dariobalinzo.task.ElasticSourceTask.fetchLastOffset(ElasticSourceTask.java:215)

This is the code of the Connector creation request:
{
  "name": "el-source",
  "config": {
    "connector.class": "com.github.dariobalinzo.ElasticSourceConnector",
    "tasks.max": "1",
    "es.host": "host.docker.internal",
    "es.port": "9201",
    "index.prefix": "persons",
    "topic.prefix": "persons",
    "incrementing.field.name": "_id"
  }
}

I have tried different values for the field "incrementing.field.name" with no luck.
Any idea?
Thanks!

**Comment by DarioBalinzo** [comment]
Hey! Sorry for my late response.
I think that here the problem is the special "_id" field used as "incrementing.field.name".
Did you tried using a normal field part of the body of the document?

Dario
