### ISSUE TITLE
jar with deps in releases

### ISSUE THREAD

**Issue by konstan** [DarioBalinzo/kafka-connect-elasticsearch-source#17]
Would it be possible to produce jar w/ deps along with the release?

**Comment by DarioBalinzo** [comment]
Yep, starting from version 1.1 I will try to include the jar in the release.

**Comment by DarioBalinzo** [comment]
Here there is the link to the new version, where you can find the jar with deps: https://github.com/DarioBalinzo/kafka-connect-elasticsearch-source/releases/tag/v1.1

**Comment by konstan** [comment]
Great news - thanks. But the difference between .jar and .zip is less than 3MB. Can we have .jar directly available?
It's just an extra friction needing to have unzip in the container and then run extraction. For example here (I'm getting .jar form the fork):

```
  kafka:
    image: confluentinc/cp-kafka:6.0.0
...
    command:
      - bash
      - -xc
      - |
        ###
        echo "Launching Kafka"
        /etc/confluent/docker/run &
        ### Install ES Connect source
        mkdir -p /usr/share/java/elastic-source-connect
        curl -L --output /usr/share/java/elastic-source-connect/elastic-source-connect-1.1-jar-with-dependencies.jar \
            https://github.com/konstan/kafka-connect-elasticsearch-source/releases/download/v1.1/elastic-source-connect-1.1-jar-with-dependencies.jar
```

**Comment by DarioBalinzo** [comment]
Sure, no problem. I've uploaded also the unzipped version.

**Comment by konstan** [comment]
Fantastic 👍
