### ISSUE TITLE
Pulling data on create of source connector after it is not pulling latest data from ES

### ISSUE THREAD

**Issue by vaibhavpatil123** [DarioBalinzo/kafka-connect-elasticsearch-source#2]
Pulling data on create of source connector after it is not pulling latest data from ES

Configured :
{
    "name": "elastic-source-logs",
    "config": {
        "connector.class": "com.github.dariobalinzo.ElasticSourceConnector",
        "topic.prefix": "logs",
        "es.host": "elastic",
        "tasks.max": "1",
        "incrementing.field.name": "timestamp",
        "name": "elastic-source-logs",
        "es.port": "9200",
        "index.prefix": "logs,
	
		"poll.interval.ms":"10000"
	"timestamp.delay.interval.ms":"3000"
    }}

This will pulling data from ES only once after that it is not pulling again new changes from ES .

Is there any configuration paramter to configure pull interval ????

**Comment by vaibhavpatil123** [comment]
https://github.com/DarioBalinzo/kafka-connect-elasticsearch-source/blob/master/src/main/java/com/github/dariobalinzo/ElasticSourceConnectorConfig.java

**Comment by DarioBalinzo** [comment]
As you pointed out there are params related to the polling ms. But be sure to use an incrementing field as incrementing.field.name otherwise you will loose some updates
