### ISSUE TITLE
question: '-' removed from the attributes of the JSON value

### ISSUE THREAD

**Issue by konstan** [DarioBalinzo/kafka-connect-elasticsearch-source#21]
Hi @DarioBalinzo 

I see that the ES connect code removes dashes from the attributes: in my case `current-time` turns into `currenttime` etc. Is it intentional? When working with Kafka I can have keys and attributes of JSON values with dashes, as well as in ksqlDB column names with dashes are fine (just need to quote them in KSQL queries). 
Why is it that you are removing them in the ES connect?
Thank you.

**Comment by DarioBalinzo** [comment]
Hey @konstan,
Yes, it is intentional. I'm converting the names in order to be compatible with the Avro serialization (see here: https://avro.apache.org/docs/1.8.1/spec.html#names).

Is this a blocking problem for you?
Actually, I might enable a config to turn on/off this name conversion if you think this might be useful (the conversion logic is isolated in a single Java class ).

**Comment by konstan** [comment]
Hi @DarioBalinzo ,

Yes, our code generates loads of attributes with dashes. It would be simpler for the processing downstream if the attributes wouldn't change. If it's possible, a configuration parameter would be highly appreciated.
Thank you!

**Comment by DarioBalinzo** [comment]
Hi @feed3r, would you like to help me in developing this issue?

Please make `AvroName` class non static, and create a new interface for its public methods (calling the new interface something like `FieldNameConverter`).
Then you can create also a `NopNameConversion` class (that implements `FieldNameConverter`) that is not changing the original name.

Finally in the `ElasticSourceTask` class initialize both `SchemaConverter` and `StructConverter`, passing in the constructor an instance of `AvroName`
or `NopNameConversion` depending on the user configuration.

For testing, please refer to `SchemaConverterTest` and `ElasticSourceTaskTest` files.

**Comment by DarioBalinzo** [comment]
Hi @konstan,
we just released version 1.2 with the new config.

You can find the description of the new param in the readme (`fieldname_converter`).

**Comment by konstan** [comment]
@DarioBalinzo I validated the feature and it works correctly in my case. Thanks a lot!
