### ISSUE TITLE
Accessing _index, _id fields?

### ISSUE THREAD

**Issue by albertwgchu** [DarioBalinzo/kafka-connect-elasticsearch-source#28]
Hi @DarioBalinzo,

I was wondering if there's a way to access the ElasticSearch _id field?  e.g.

{
"_index": "xxx",
"_id": 1,
"_source": {
...
}

**Comment by DarioBalinzo** [comment]
Hi,
right now both `_id` and `_index` are discarded, since only the source part is sent to kafka.

But we will add also the these fields in the next version of the connector.

**Comment by DarioBalinzo** [comment]
Hi @albertwgchu, starting from version 1.4 you can find the fileds `es-id` and `es-index` fields in the messages produced by the connector.

**Comment by albertwgchu** [comment]
I just tried it and it worked.  The fields are actually esid and esindex, but that is fine.  Thanks again

**Comment by DarioBalinzo** [comment]
Cool,
yes the config `fieldname_converter` by default is `avro`, but you can set it to `nop` to avoid fields renaming. Some character must be removed (like `-`) to be correctly serialized as avro field name.
