### ISSUE TITLE
avoid wide matching of indexes with index.prefix

### ISSUE THREAD

**Issue by konstan** [DarioBalinzo/kafka-connect-elasticsearch-source#32]
Hello @DarioBalinzo ,

I have two indexes in ES `nuvla-nuvlabox` and `nuvla-nuvlabox-status` and with the configuration below, I noticed, I'm getting messages twice in `es_nuvla-nuvlabox-status`. I added `"elastic-source-nuvlabox"` much later due to new requirements.

```
[root@31e4e221f046 appuser]# cat /etc/kafka/elastic-source-nuvlabox.json
{   "name": "elastic-source-nuvlabox",
    "config": {"connector.class":"com.github.dariobalinzo.ElasticSourceConnector",
               "tasks.max": "1",
               "es.host" : "es",
               "es.port" : "9200",
               "index.prefix" : "nuvla-nuvlabox",
               "topic.prefix" : "es_",
               "incrementing.field.name" : "updated",
               "fieldname_converter": "nop"
    }
}
[root@31e4e221f046 appuser]# cat /etc/kafka/elastic-source-nuvlabox-status.json
{   "name": "elastic-source-nuvlabox-status",
    "config": {"connector.class":"com.github.dariobalinzo.ElasticSourceConnector",
               "tasks.max": "1",
               "es.host" : "es",
               "es.port" : "9200",
               "index.prefix" : "nuvla-nuvlabox-status",
               "topic.prefix" : "es_",
               "incrementing.field.name" : "updated",
               "fieldname_converter": "nop"
    }
}
[root@31e4e221f046 appuser]#
```
I understand this can be fixed by removing `elastic-source-nuvlabox-status` connector. However, what will happen if I add e.g. `nuvla-nuvlabox-telem` index? I don't want it to end up in Kafka as `es_nuvla-nuvlabox-telem`.

Maybe, adding an optional `index.name` (or comma-separated `index.names`) parameter for the index(s) strict definition would be a solution?

Thank you.

**Comment by DarioBalinzo** [comment]
Hi @konstan, 
yes I like the idea of an optional comma-separated `index.names`. I will try to release it in the next few weeks.

However, you can also deploy only one instance of the connector, handling many tasks (configured by the `tasks.max`): for instance in you case you can have a single instance of the connector with two parallel task, each task working on an index ( in your case you just need to specify the prefix `nuvla-nuvlabox` for both).

**Comment by konstan** [comment]
Thanks. Having `index.names` would be awesome.

> you can have a single instance of the connector with two parallel tasks, each task working on an index ( in your case you just need to specify the prefix nuvla-nuvlabox for both).

I'm going to do the following now with 

```
{   "name": "elastic-source-nuvlabox",
    "config": {"connector.class":"com.github.dariobalinzo.ElasticSourceConnector",
               "tasks.max": "1",
               "es.host" : "es",
               "es.port" : "9200",
               "index.prefix" : "nuvla-nuvlabox",
               "topic.prefix" : "es_",
               "incrementing.field.name" : "updated",
               "fieldname_converter": "nop"
    }
}
```
on ES having two indexes `nuvla-nuvlabox` and `nuvla-nuvlabox-status`, and hoping I will get `es_nuvla-nuvlabox` and `es_nuvla-nuvlabox-status` topics. I'll update you shortly.

However, when I add `nuvla-nuvlabox-foo`, I don't want it to appear in Kafka.  

Is `"tasks.max": "N"` is the number of Kafka producers per ES index, or this is the number of indexes matched by `index.prefix`? In the second case, the question is how the indexes are selected - sorted lexicographically? Then, with `tasks=2`, `nuvla-nuvlabox-foo` will appear in Kafka, but `nuvla-nuvlabox-status` not.  Just guessing, because `tasks.max` is not documented here https://github.com/DarioBalinzo/kafka-connect-elasticsearch-source/blob/master/README.md

**Comment by konstan** [comment]
Just confirmed that `"tasks.max"` doesn't influence the number of selected indexes, and with the below single config 

```
[root@c4749e328469 appuser]# cat /etc/kafka/elastic-source-nuvlabox.json
{   "name": "elastic-source-nuvlabox",
    "config": {"connector.class":"com.github.dariobalinzo.ElasticSourceConnector",
               "tasks.max": "1",
               "es.host" : "es",
               "es.port" : "9200",
               "index.prefix" : "nuvla-nuvlabox",
               "topic.prefix" : "es_",
               "incrementing.field.name" : "updated",
               "fieldname_converter": "nop"
    }
}
[root@c4749e328469 appuser]# kafka-topics --bootstrap-server localhost:9092 --list | grep nuvlabox
es_nuvla-nuvlabox
es_nuvla-nuvlabox-status
[root@c4749e328469 appuser]#
```

I'm getting all `"index.prefix"` matched ones in Kafka. This will do for me for now. But having `index.names` for a more granular selection of the ES indexes would be better.
Thanks!

**Comment by DarioBalinzo** [comment]
Yes, "`tasks.max`" doesn't influence the number of selected indexes, it controls the number of concurrent activities that the connector will run (e.g. if the prefix matches 10 indices, 2 concurrent tasks will fetch the data, each one from 5 indices). Thanks for signaling that the description is missing the in the docs, I will add shortly.

The main goal of `tasks.max` and `index.prefix` is to avoid to create multiple instances of the connector for each index, so that a single instance is able to mange many indices in parallel.
Note that the indices list is read only at the startup of the connect: if you will add a new index with the same prefix, then connector should be restarted to fetch data from the new index.

However I will add the  `index.names` config as I think it is reasonable to have a more fine grain control on what is feched and what is not.
