### ISSUE TITLE
Schema Exception- When a complex property (type as 'nested') is included in a ES document

### ISSUE THREAD

**Issue by Siddmahi** [DarioBalinzo/kafka-connect-elasticsearch-source#43]
**ES document mapping:**
PUT /test-websitesources
{
  "mappings": {
    "source": {
      "properties": {
        "sourceId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "weblinks": {
         "type":"nested",
         "properties" : {
              "id" : {
                "type" : "text"
              },
              "name" : {
                "type" : "text"
              }
            }
        },
        "updated_date": {
          "type": "date"
        },
        "createdDate": {
          "type": "date"
        }
      }
    }
  }
}

**Valid Scenario:**
Kafka connectors are successfully able to pull this data and I can view this under topics
"source": {
    "sourceId": "s1",
    "weblinks": {
        "id": "street",
        "name": "www.street.com"
    },
    "updated_date": "2021-04-18T17:54:49.643073Z",
    "createdDate": "2020-02-18T20:32:41.1775655Z"
}

**Failing Scenario (passing the weblinks field as array):**
"source": {
    "sourceId": "s1",
    "weblinks": [{
            "id": "afr",
            "name": "www.afr.com"
        }
    ],
    "updated_date": "2021-04-17T17:54:49.643073Z",
    "createdDate": "2020-02-18T20:32:41.1775655Z"
}
It fails. I am getting the exception like below

**Exception:**
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)

Caused by: org.apache.avro.SchemaParseException: Empty name
	at org.apache.avro.Schema.validateName(Schema.java:1523)

**Comment by DarioBalinzo** [comment]
Hi @Siddmahi, thank you for the detailed description.

I will try to reproduce it and fix it in few days.

**Comment by Siddmahi** [comment]
Hi @DarioBalinzo, Did you find time to reproduce the issue?

**Comment by DarioBalinzo** [comment]
Hi @Siddmahi, not yet, but I'm planning to look into it during the next week.

**Comment by Siddmahi** [comment]
Hi @DarioBalinzo, If I may suggest an approach, Can we have multiple indexes point to the same topic? Currently, we are using aliases(index) so multiple index versions(index_v1, index_v2, etc) are created with each topic. So is it possible to have multiple indexes versions to the same single topic? 
Thanks in advance :)

**Comment by DarioBalinzo** [comment]
Hi @Siddmahi ,
sorry for my late response, this is a very busy period for me!

The problem is not related to multiple indices or aliasing.

However the problem here might be in the avro serialization: in avro a field has only one possibile type (scalar or array, not both like weblinks in your example). 

Can you try to configure the connect to use json serialization to see if you can fix the issue and send the messages correctly?
https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained/#choosing-serialization-format
