### ISSUE TITLE
Elasticsearch api 7.x

### ISSUE THREAD

**Issue by DarioBalinzo** [DarioBalinzo/kafka-connect-elasticsearch-source#5]
I'm updating the elasticsearch and the kafka connect api to the latest version.

I'm planning to refactor the code and tests to improve code quality and reduce bugs.

**Comment by albertwgchu** [comment]
Hi, thank you for setting up this project.  I'm wondering if you will add support for ElasticSearch using HTTPS in your upcoming release.  This fork has added a config option called es.scheme which defaults to HTTP but can be overridden to HTTPS.  

https://github.com/inspectorioinc/kafka-connect-elasticsearch-source

**Comment by DarioBalinzo** [comment]
Hi @albertwgchu,thank you for the suggestion. 

Yes, I will insert it in the future release after cleaning and refactoring of the code. The project also needs better integration tests using test containers. 

After these development I will add the https support.
