### ISSUE TITLE
partition elasticsearch records by values

### ISSUE THREAD

**Issue by RuMcClu** [DarioBalinzo/kafka-connect-elasticsearch-source#50]
Hi there,

I'm currently using this repo (thanks very much by the way) and I'm hoping to take my JSON documents and use a certain key to either partition them or send them to different topics. One approach is to write a custom JSON deserialiser that reads from the elasticsearch source topic, but I was wondering if you could select a key with a certain value with ES source and only pull those documents in that had that key value pair.

Thanks in advance

**Comment by DarioBalinzo** [comment]
Hi, thanks for your feedback!

You can have a look on these feature that are working out of the box with every kafka connector:
https://docs.confluent.io/platform/current/connect/transforms/overview.html 
You can find information about adding new fields, transforming the messages etc..

And probably you may find useful this particular transform that ovverrides the kafka topic looking at the values of the message fields:
https://docs.confluent.io/platform/current/connect/transforms/extracttopic.html#extracttopic

Is that similar to what you need?

However in future I think I may add a custom query config, to let the users decide which documents are extracted from the elastic index/indices.

**Comment by RuMcClu** [comment]
Thanks very much! I used this and it worked very well.
