### ISSUE TITLE
Resetting the incrementing field?

### ISSUE THREAD

**Issue by albertwgchu** [DarioBalinzo/kafka-connect-elasticsearch-source#55]
Hi, I'm wondering if there's a good way to reset the incrementing field?  For example I want to run the connector on all the data since the beginning of time again.

**Comment by DarioBalinzo** [comment]
Hi, the offset of the incrementing field is stored in the `connect-offset` topic, as any standard connector. You can find here more information: https://rmoff.net/2019/08/15/reset-kafka-connect-source-connector-offsets/

**Comment by albertwgchu** [comment]
Thanks for the link!
