### ISSUE TITLE
Does this connector support elastic OpenDistro

### ISSUE THREAD

**Issue by phoenixml** [DarioBalinzo/kafka-connect-elasticsearch-source#58]
Hi Dario,

I tried the plugin with opendistro Elastic version, and I added username and password to my connector conf however I am getting this result once I registered the connector:
 
```
kafka-connect    |  (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:354)
kafka-connect    | [2021-09-26 05:19:29,894] ERROR [-es-source|worker] error in searching index names (com.github.dariobalinzo.elastic.ElasticRepository:190)
kafka-connect    | [2021-09-26 05:19:29,895] ERROR [Worker clientId=connect-1, groupId=kafka-connect] Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1376)
kafka-connect    | java.lang.RuntimeException: org.
```

**Registration conf:**
curl -X PUT http://192.168.1.100:8083/connectors/es-source/config -H "Content-Type: application/json" -d '{
"connector.class": "com.github.dariobalinzo.ElasticSourceConnector",
"tasks.max": "2",
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"errors.retry.timeout": "-1",
"errors.log.enable": true,
"errors.log.include.messages": true,
"es.host": "192.168.1.50",
"es.port": "9200",
"es.user": "admin",
"es.password": "temppass",
"connection.attempts": "5",
"connection.backoff.ms": "10000",
"index.prefix": "log",
"incrementing.field.name": "@timestamp",
"topic.prefix": "My_"
}'

Thank you in advance

**Comment by DarioBalinzo** [comment]
The connector is compatible to any version of elasticsearch that uses basic authentication, so also open distro should work.
Can you share the full stack trace if possible?

**Comment by phoenixml** [comment]
That's true @DarioBalinzo  thank you, I moved the connector to another machine and it worked well not sure what was the main reason to trigger this error. Closed
