### ISSUE TITLE
Errors using kafka-connect-elasticsearch-source:1.4.2

### ISSUE THREAD

**Issue by milnomada** [DarioBalinzo/kafka-connect-elasticsearch-source#60]
Hello,

I'm using the elasticsearch-source:1.3 with success. 
I install it with the confluent-hub client by:
```
confluent-hub install --no-prompt dariobalinzo/kafka-connect-elasticsearch-source:1.3
```

I need to use, the `filters.blacklist` which as far as I know are available in `1.4.2` branch of this repository.

I tried to install it 
```
confluent-hub install --no-prompt dariobalinzo/kafka-connect-elasticsearch-source:1.4.2
```
No success.

Then, cloned the repository, moved to `1.4.2` branch and run the `mvn` build  command: `mvn clean package -DskipTests`
Build was ok.

I'm placing the generated jar into the `plugin.path` set in settings, which would be `/usr/share/confluent-hub-components`, and so to the `/etc/kafka-connect/jars/` folder.
If I use the `elastic-source-connect-1.4-jar-with-dependencies.jar` I got the following error:

```
kafka kafka-cp-kafka-connect-5f7d74847b-hrbl5 cp-kafka-connect-server [2021-09-29 12:22:58,664] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed)
kafka kafka-cp-kafka-connect-5f7d74847b-hrbl5 cp-kafka-connect-server java.lang.NoSuchFieldError: DEFAULT_SOCKET_CONNECTION_SETUP_TIMEOUT_MS
kafka kafka-cp-kafka-connect-5f7d74847b-hrbl5 cp-kafka-connect-server  	at org.apache.kafka.connect.runtime.distributed.DistributedConfig.<clinit>(DistributedConfig.java:245)
kafka kafka-cp-kafka-connect-5f7d74847b-hrbl5 cp-kafka-connect-server  	at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:95)
kafka kafka-cp-kafka-connect-5f7d74847b-hrbl5 cp-kafka-connect-server  	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:80)
```
which prevents kafka-connect from starting up.

If I use the `elastic-source-connect-1.4.jar`, I got:
```
kafka kafka-cp-kafka-connect-68f487696-c6fbt cp-kafka-connect-server [2021-09-29 12:37:56,765] ERROR WorkerConnector{id=elastic-source-20210710} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
kafka kafka-cp-kafka-connect-68f487696-c6fbt cp-kafka-connect-server java.lang.NoClassDefFoundError: org/apache/http/client/CredentialsProvider
kafka kafka-cp-kafka-connect-68f487696-c6fbt cp-kafka-connect-server   	at com.github.dariobalinzo.elastic.ElasticConnectionBuilder.build(ElasticConnectionBuilder.java:77)
```
which also prevents kafka-connect from starting up.

Using as base image the `confluentinc/cp-kafka-connect-base:6.1.1` 

Is there anything to do to overcome these errors?

Thanks for any clue

**Comment by DarioBalinzo** [comment]
Hi,
you can download the jar directly here:
https://github.com/DarioBalinzo/kafka-connect-elasticsearch-source/releases/tag/v1.4.2

version 1.4.2 is not yet published on the confluent hub.

In this issue you can also find an example of a dockerfile running v1.4.2:

https://github.com/DarioBalinzo/kafka-connect-elasticsearch-source/issues/54

**Comment by milnomada** [comment]
Hi Dario,

I'm using the approach to install the `jar.zip` version with the `confluent-hub install` command, 
I updated the base image from `confluentinc/cp-kafka-connect-base:6.1.1` to `confluentinc/cp-kafka-connect-base:6.0.1` as well.

Now it works great. I do not see the previous serialization errors, so even no need to use the `filters`.

Thanks for the quick and effective reply!
