### ISSUE TITLE
Missing records?

### ISSUE THREAD

**Issue by albertwgchu** [DarioBalinzo/kafka-connect-elasticsearch-source#65]
Hi,

I've noticed sometimes records can be missed by the connector.  I think it has to do with batched writes and the frequency of polling based on my experiments.  

I'm using the Kafka message offset as the incrementing field.

I've adjusted the polling interval from the default 5 seconds to 30 minutes in some cases.  So far this has helped quite a bit.  

Just wondering if anyone else has come across this or has a different strategy?

**Comment by DarioBalinzo** [comment]
Hi, this might be related also to the refresh time interval in elasticsearch. When you are indexing data into elastic, using other tools, then not all the data is always put in elastic at the same time, and there is not the concept of transaction on elastic. So every "refresh time interval" some data is available to the search.

As you suggested, you can tune the polling interval and trying also to tune the page size of each poll request.
