### ISSUE TITLE
Now that ElasticSourceConnector is working, how to consume messages using Java from Kafka Topic? 

### ISSUE THREAD

**Issue by srinivasagank** [DarioBalinzo/kafka-connect-elasticsearch-source#85]
I configured ElasticSourceConnector successfully, and it is working.
Now I want to consume messages that comes to Kafka Topic using Java code.
Do I have to use JSON serializer/deserializer, or how do I receive Java object?
I am using my_awesome_index as index prefix.
Kindly share the Java code example.
Thanks
Srinivasagan

**Comment by srinivasagank** [comment]
In my Spring Boot Application...

**Comment by srinivasagank** [comment]
POST /my_awesome_index/_doc
{
  "greeting":"Hello",
  "receiver":"World",
  "@timestamp": "2022-02-02T16:38:53.0870292"
  
}

**Comment by srinivasagank** [comment]
name=es-source
connector.class=com.github.dariobalinzo.ElasticSourceConnector
tasks.max=1
es.host=localhost
es.port=9200
index.prefix=my_awesome_index
topic.prefix=es_
incrementing.field.name=@timestamp

**Comment by DarioBalinzo** [comment]
> I configured ElasticSourceConnector successfully, and it is working. Now I want to consume messages that comes to Kafka Topic using Java code. Do I have to use JSON serializer/deserializer, or how do I receive Java object? I am using my_awesome_index as index prefix. Kindly share the Java code example. Thanks Srinivasagan

It depends if you have used json serialization or avro serialization in the connector. 
You can also use the kafka console consumer or kafka avro console consumer to check the format of the topics in you kafka cluster.
